# Site settings
title: MTube
email: your-email@domain.com
description: Using AR to fuel note-taking and resource sharing
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://MTube.github.io" # the base hostname & protocol for your site
twitter_username: MTube
github_username:  MTube

# Build settings
# highlighter: redcarpet
markdown: kramdown

collections:
- math

collections:
  math:
    output: true

defaults:
  -
    scope:
      path: ""
      type: math
    values:
      layout: page